SELECT * FROM TB_BOARD;

DROP TABLE TB_BOARD;

DROP SEQUENCE seq_tb_board_idx;

CREATE TABLE TB_BOARD
(
    IDX NUMBER PRIMARY KEY,
    PARENT_IDX NUMBER,
    TITLE VARCHAR2(100) NOT NULL,
    CONTENTS VARCHAR2(4000) NOT NULL,
    HIT_CNT NUMBER NOT NULL,
    DEL_GB VARCHAR2(1) DEFAULT 'N' NOT NULL,
    CREA_DTM DATE DEFAULT SYSDATE NOT NULL,
    CREA_ID VARCHAR2(30) NOT NULL
);

COMMENT ON TABLE TB_BOARD IS '게시판';
COMMENT ON COLUMN TB_BOARD.IDX IS '인덱스';
COMMENT ON COLUMN TB_BOARD.PARENT_IDX IS '부모글 인덱스';
COMMENT ON COLUMN TB_BOARD.TITLE IS '제목';
COMMENT ON COLUMN TB_BOARD.CONTENTS IS '내용';
COMMENT ON COLUMN TB_BOARD.HIT_CNT IS '조회수';
COMMENT ON COLUMN TB_BOARD.DEL_GB IS '삭제구분';
COMMENT ON COLUMN TB_BOARD.CREA_DTM IS '생성일자';
COMMENT ON COLUMN TB_BOARD.CREA_ID IS '생성자 ID';

CREATE SEQUENCE SEQ_TB_BOARD_IDX
START WITH 1
INCREMENT BY 1
NOMAXVALUE
NOCACHE;

-- FILE up/down load시 사용될 테이블
CREATE TABLE TB_FILE
(
  IDX   NUMBER,
  BOARD_IDX NUMBER NOT NULL,
  ORIGINAL_FILE_NAME VARCHAR2(260 BYTE) NOT NULL,
  STORED_FILE_NAME VARCHAR2(36 BYTE) NOT NULL,
  FILE_SIZE NUMBER,
  CREA_DTM  DATE DEFAULT SYSDATE NOT NULL,
  CREA_ID   VARCHAR2(30 BYTE) NOT NULL,
  DEL_GB    VARCHAR2(1 BYTE) DEFAULT 'N' NOT NULL,
  PRIMARY KEY (IDX)
);

-- FILE up/down load와 관련된 파일 시퀀스
CREATE SEQUENCE SEQ_TB_FILE_IDX
  START WITH 1
  INCREMENT BY 1
  NOMAXVALUE
  NOCACHE;

SELECT
    IDX,
    TITLE,
    HIT_CNT,
    CREA_DTM
FROM
    TB_BOARD
WHERE 
	DEL_GB = 'N'
ORDER BY IDX DESC;

INSERT INTO TB_BOARD
(
    IDX,
    TITLE,
    CONTENTS,
    HIT_CNT,
    DEL_GB,
    CREA_DTM,
    CREA_ID
)
VALUES
(
    SEQ_TB_BOARD_IDX.NEXTVAL,
    '제목',
    '내용',
    0,
    'N',
    SYSDATE,
    'Admin'
);

-- 페이징 쿼리
SELECT 
	AAA.*
FROM(
  SELECT COUNT(*) OVER() AS TOTAL_COUNT,
    AA.*
  FROM(
    SELECT
      ROW_NUMBER() OVER (ORDER BY IDX DESC) RNUM,
      IDX,
      TITLE,
      HIT_CNT,
      CREA_DTM
    FROM 
      TB_BOARD
    ) AA
	) AAA
WHERE
	AAA.RNUM BETWEEN 0 AND 20;

-- CREATE TEST DATA
BEGIN
	FOR i IN 1..500 LOOP
	INSERT INTO TB_BOARD(IDX, TITLE, CONTENTS, HIT_CNT, DEL_GB, CREA_DTM, CREA_ID)
	VALUES (SEQ_TB_BOARD_IDX.NEXTVAL, '제목 '||i, '내용'||i, 0, 'N', SYSDATE, 'Admin');
	END LOOP;
END;
/

COMMIT;